[features]
seeds = false
[programs.localnet]
autopay = "78vov3JfntD46gxEAFhtu2tTfonpEfkbzMSDe9aNTHbP"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/braeden/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

# [[test.genesis]]
# address = "6chEwh4WPk85uD9Z6SxfmBgjywwFhF6q3mP1Vp6s9bWE"
# program = "./deps/cronos/target/deploy/cronos_health.so"

# [[test.genesis]]
# address = "7dgApA7ixgamh8TRJDVqhsPVDxn4RVQgW93xgcSqpzWQ"
# program = "./deps/cronos/target/deploy/cronos_network.so"

# [[test.genesis]]
# address = "6DAy7xoDMkoCsvXiVqHw7mXWL2a9Nv6TMykL5QkX7Jiu"
# program = "./deps/cronos/target/deploy/cronos_pool.so"

# [[test.genesis]]
# address = "7XgnJEERdx6SXiXbv1TqSe1XCYCa81BVC5UYRA1mnN1o"
# program = "./deps/cronos/target/deploy/cronos_scheduler.so"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.clone]]
address = "6chEwh4WPk85uD9Z6SxfmBgjywwFhF6q3mP1Vp6s9bWE"

[[test.clone]]
address = "7dgApA7ixgamh8TRJDVqhsPVDxn4RVQgW93xgcSqpzWQ"

[[test.clone]]
address = "6DAy7xoDMkoCsvXiVqHw7mXWL2a9Nv6TMykL5QkX7Jiu"

[[test.clone]]
address = "7XgnJEERdx6SXiXbv1TqSe1XCYCa81BVC5UYRA1mnN1o"
